name: Deploy by runner

on:
  push:
    branches: [ "master", "develop", "ci-cd" ]

jobs:
  prepare-environment:
    runs-on: self-hosted
    steps:
      - name: Stop and remove containers, networks
        run: docker-compose -f docker/docker-compose.yml down
      - name: Remove unused data
        run: docker system prune -a -f
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker-compose
        run: docker-compose -f docker/docker-compose.yml up -d