name: Deploy by runner

on:
  push:
    branches: [ "master", "develop", "ci-cd" ]

jobs:
  prepare-prod:
    runs-on: self-hosted
    steps:
      - name: Stop and remove containers, networks
        run: docker-compose -f docker/docker-compose.yml down
      - name: Remove unused data
        run: docker system prune -a -f
  deploy-on-prod:
    runs-on: self-hosted
    environment: prod
    needs: prepare-prod
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker-compose
        run: docker-compose -f docker/docker-compose.yml up -d